Fix
seamusic-official/seamusic-backend pull request #33
Opened 2024-10-17 10:09 UTC by Nalsher

Fixed models

2024-10-17 18:08 UTC, dmkjfs commented on src/dtos/database/albums.py
>      id: int
так подожди а где используется этот класс?

2024-10-17 18:10 UTC, dmkjfs commented on src/dtos/database/albums.py
надо добавить AlbumItem или что-то типа такого и помещать в список в AlbumResponse. класс Album удалить

2024-10-17 18:11 UTC, dmkjfs commented on src/dtos/database/squads.py
>      created_at: datetime
Б - бизнес-логика

2024-10-17 18:14 UTC, dmkjfs commented on src/models/__init__.py
> -    ProducerProfile, user_to_playlists_association, user_to_comments_association, squad_to_producer_association, \
скобки

2024-10-17 19:33 UTC, dmkjfs requested changes
- модели привести в соответствие с проекцией
- дто привести в соответствие с моделями
- пофикисть мелочи и вернуть релейшншипы

2024-10-17 19:33 UTC, dmkjfs commented on src/models/beats.py
> +    name: Mapped[str] = mapped_column(nullable=False)
это так в проекции? просто тут title ак будто бы логично

2024-10-17 19:33 UTC, dmkjfs commented on src/models/beats.py
> -    created_at: Mapped[date] = mapped_column(nullable=False)
зря убрал

2024-10-17 19:33 UTC, dmkjfs commented on src/models/beats.py
> -    created_at: Mapped[date] = mapped_column(nullable=False)
зря убрал

2024-10-17 19:33 UTC, dmkjfs commented on src/models/beats.py
> -    created_at: Mapped[date] = mapped_column(nullable=False)
зря убрал

2024-10-17 19:33 UTC, dmkjfs commented on src/models/chat.py
> +    text: Mapped[str] = mapped_column(nullable=False)
интересно

2024-10-17 19:33 UTC, dmkjfs commented on src/models/chat.py
> +    text: Mapped[str] = mapped_column(nullable=False)
а почему текст? или опять проекция

2024-10-17 19:33 UTC, dmkjfs commented on src/models/comments.py
>  class BaseComment(Base):
и еще интересно почему коммент именно базовый. Типа есть еще какой-то наследующийся коммент

2024-10-17 19:33 UTC, dmkjfs commented on src/models/licenses.py
> -        argument="User",
классика

2024-10-17 19:33 UTC, dmkjfs commented on src/models/messages.py
> +    text: Mapped[str] = mapped_column(nullable=False)
author, created_at, updated_at?

2024-10-17 19:33 UTC, dmkjfs commented on src/models/tracks.py
> +    description: Mapped[str] = mapped_column(nullable=False)
почему nullable=False

2024-10-17 19:33 UTC, dmkjfs commented on tests/repositories/database/test_auth.py
проваливаются что ли тесты

2024-10-17 19:33 UTC, dmkjfs commented on tests/repositories/database/test_auth.py
хотя че я спрашиваю то

2024-10-18 13:36 UTC, Nalsher commented on src/dtos/database/albums.py
Ок

2024-10-18 13:40 UTC, Nalsher commented on Makefile
> +	poetry run pytest -s --verbose
Флаг -s забыл убрать, verbose вроде показывает какой тест пройден, какой провален

2024-10-18 13:59 UTC, Nalsher commented on src/models/tracks.py
> +    description: Mapped[str] = mapped_column(nullable=False)
В проекции он ненулевой

2024-10-18 14:03 UTC, Nalsher commented on src/models/messages.py
> +    text: Mapped[str] = mapped_column(nullable=False)
В проекции у нас created_at, updated_at в Base определены

2024-10-18 14:04 UTC, Nalsher commented on src/models/beats.py
> +    name: Mapped[str] = mapped_column(nullable=False)
В проекции так

2024-10-18 14:05 UTC, Nalsher commented on src/models/chat.py
> +    text: Mapped[str] = mapped_column(nullable=False)
Опять проекция

2024-10-18 14:05 UTC, Nalsher commented on src/models/comments.py
>  class BaseComment(Base):
Забыл сменить название

2024-10-19 16:20 UTC, dmkjfs approved these changes
пофиг мержим в ветку, там доделаем

2024-10-19 16:22 UTC, merged